// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CompteService.proto

package ma.emsi.grpc.stubs;

public interface GetComptesByTypeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetComptesByTypeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.TypeCompte type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.TypeCompte type = 1;</code>
   * @return The type.
   */
  ma.emsi.grpc.stubs.TypeCompte getType();
}
