// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CompteService.proto

package ma.emsi.grpc.stubs;

public interface GetTotalSoldeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetTotalSoldeRequest)
    com.google.protobuf.MessageOrBuilder {
}
