// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CompteService.proto

package ma.emsi.grpc.stubs;

public interface SaveCompteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SaveCompteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Compte compte = 1;</code>
   * @return Whether the compte field is set.
   */
  boolean hasCompte();
  /**
   * <code>.Compte compte = 1;</code>
   * @return The compte.
   */
  ma.emsi.grpc.stubs.Compte getCompte();
  /**
   * <code>.Compte compte = 1;</code>
   */
  ma.emsi.grpc.stubs.CompteOrBuilder getCompteOrBuilder();
}
